Jenkins job enabled to be triggered manually
ucgmsim/Pre-processing pull request #159
Opened 2020-11-24 04:02 UTC by sungeunbae

2020-11-24 22:43 UTC, sungeunbae commented
Can one of the admins verify this patch?

2020-11-27 01:03 UTC, shot0829 requested changes

2020-11-27 01:03 UTC, shot0829 commented on Jenkinsfile
> +		rm -rf /tmp/${env.JOB_NAME}/*
a non-zero check would be nice.
if [ ! -z ${env.JOB_NAME} ]

2020-11-27 01:11 UTC, shot0829 approved these changes

2020-11-27 01:11 UTC, merged