I need this pert file
ucgmsim/Pre-processing pull request #182
Opened 2021-07-01 21:23 UTC by jasonmotha

Merging this guy from 6 months ago. But I think he needs a home.

2021-07-01 21:34 UTC, jpa198 submitted a review, later dismissed
Looks good

2021-07-06 21:47 UTC, sungeunbae requested changes
Good in general - a comment for n_process==1 assertion error will be all I'd like to have added

2021-07-06 21:47 UTC, sungeunbae commented on srf_generation/velocity_model_generation/generate_3d_velocity_model_perturbation.py
> +        if n_processes == 1:
It feels slightly odd to raise an assertion error for the default value for n_processes. I guess there is a good reason for this, and a comment will be helpful.

2021-07-07 03:46 UTC, jpa198 requested changes
All those changes to gen_3d seem like left over debugging changes? 
For a permanent change the stderr stuff should have a flag to enable stderr output and the n_processes thing should be changed to "if n_proc==1:  loop else: pool" and an error message saying to try again with n_proc=1 if it fails

2021-07-07 04:08 UTC, jasonmotha commented
@sungeunbae @jpa198 There are a few more changes that need to be made to generate_3d_perturbations. So this PR is just going to be for the configuration file. Can you please review this once more?

2021-07-07 04:15 UTC, sungeunbae approved these changes

2021-07-07 04:23 UTC, jpa198 approved these changes

2021-07-07 04:23 UTC, merged