Updated comment on Leonard2014
ucgmsim/Pre-processing pull request #234
Opened 2024-07-02 09:49 UTC by sungeunbae

There was a discussion on Leonard2010 vs Leonard2014 on Slack in regards to what we should use for the magnitude-area relations. 
https://uceqeng.slack.com/archives/CUD9MUZ4Y/p1719447280472479

We have been using LEONARD2014 for Cybershake.

Leonard2010 is on active region and Leonard2014 is on SCR (stable continental region), so we should use & cite Leonard2010 for Cybershake NZ.

However, it happens to be the underlying math is the same. 
For the future reference, I just made a comment. 

Perhaps it is better to rename it to Leonard2010 in
https://github.com/ucgmsim/qcore/blob/master/qcore/uncertainties/mag_scaling.py 
but I felt it could potentially break things in the current Cyberhsake 200m in progress...

2024-07-02 21:36 UTC, claudio525 submitted a review, later dismissed

2024-07-02 21:48 UTC, joelridden approved these changes
I feel like the comment is enough to lose confusion if it's the same math anyways

2024-07-02 21:59 UTC, lispandfound requested changes
Reading the slack channel, I wonder if it's not worth linking to it in the comment here.

2024-07-02 21:59 UTC, lispandfound commented on srf_generation/Fault.py
> +            # Note: LEONARD2014 (stable continental region (SCR) vs LEONARD2010 (active region) but the formulation is the same
```suggestion
            # Note: LEONARD2014 uses stable continental regions (SCR) vs LEONARD2010 (active region) but the formulation is the same
```

2024-07-03 20:47 UTC, AndrewRidden-Harper approved these changes

2024-07-03 21:22 UTC, sungeunbae commented on srf_generation/Fault.py
> +            # Note: LEONARD2014 (stable continental region (SCR) vs LEONARD2010 (active region) but the formulation is the same
Made the comment slightly more explicit

2024-07-03 21:45 UTC, lispandfound approved these changes

2024-07-04 00:11 UTC, joelridden approved these changes

2024-07-04 00:22 UTC, claudio525 approved these changes

2024-07-04 00:48 UTC, AndrewRidden-Harper approved these changes

2024-07-05 01:13 UTC, merged